--------- ABC CLASS ---------
WITH ITEM_SALES_ABC AS(
SELECT 
	ITEM,
	SUM(QTYSHIP * UNITPRICE) AS ITEM_SALES,
	(SELECT SUM(QTYSHIP * UNITPRICE) 
		FROM DBO.InvoiceDetailHistory I 
		JOIN DCSCIM C ON C.ITMID = I.ITEM 
		INNER JOIN DIMDATE D ON D.calendarDate = I.invoiceDate
		WHERE calendardate >= DATEADD(MONTH, -12, GETDATE())) AS TOTAL_SALES
FROM dbo.InvoiceDetailHistory I
JOIN DCSCIM C ON C.ITMID = I.ITEM
INNER JOIN DIMDATE D ON D.calendarDate = I.invoiceDate
WHERE calendardate >= DATEADD(MONTH, -12, GETDATE())
GROUP BY ITEM),

TOTAL_SALES_ABC AS(
SELECT 
	ITEM, ITEM_SALES, TOTAL_SALES,
	(ITEM_SALES/TOTAL_SALES) AS SALES_PERCENT
FROM ITEM_SALES_ABC),

CUML_SALES AS(
SELECT ITEM, ITEM_SALES, TOTAL_SALES, SALES_PERCENT,
SUM(SALES_PERCENT) OVER(ORDER BY ITEM_SALES DESC) AS CUML_TOTAL_PERCENT
FROM TOTAL_SALES_ABC
),

ABC_TABLE AS(
SELECT ITEM, ITEM_SALES, TOTAL_SALES, SALES_PERCENT, CUML_TOTAL_PERCENT,
	CASE WHEN CUML_TOTAL_PERCENT < 0.700 THEN 'A'
		WHEN CUML_TOTAL_PERCENT > 0.900 THEN 'C' ELSE 'B' END AS ABC_CLASS
FROM CUML_SALES
),



--------- XYZ CLASS ---------
ITEM_SALES_XYZ AS(
SELECT ITEM, I.FISCALPERIOD, SUM(UNITPRICE * QTYSHIP) AS SALES
FROM InvoiceDetailHistory I
JOIN DCSCIM C ON I.ITEM = C.ITMID
INNER JOIN DIMDATE D ON D.calendarDate = I.invoiceDate
WHERE calendardate >= DATEADD(MONTH, -12, GETDATE())
GROUP BY ITEM, I.FISCALPERIOD
),

SDEVP AS(
SELECT ITEM, STDEVP(SALES) AS SDEV_SALES, AVG(SALES) AS ITEM_SALES
FROM ITEM_SALES_XYZ
GROUP BY ITEM
),

COEF_VAL AS(
SELECT ITEM, SDEV_SALES, ITEM_SALES, 
	CASE WHEN ITEM_SALES = 0 THEN 0 ELSE SUM(SDEV_SALES / ITEM_SALES) END AS COEF_VAL
FROM SDEVP
GROUP BY ITEM, SDEV_SALES, ITEM_SALES
),

XYZ_TABLE AS ( SELECT *, 
	CASE
		WHEN COEF_VAL < 0.35 THEN 'X'
		WHEN COEF_VAL > 0.65 THEN 'Z'
		ELSE 'Y' END AS XYZ_CLASS
FROM COEF_VAL)


--------- JOIN ABC & XYZ CLASS ---------
SELECT *, (ABC_CLASS + XYZ_CLASS) AS ABC_XYZ
FROM ABC_TABLE A
INNER JOIN XYZ_TABLE Z
	ON A.item = Z.item
