-- -- -- -- -- -- -- -- -- -- -- -- --  
      --- DAX Equation Notes ---
-- -- -- -- -- -- -- -- -- -- -- -- --  


-- -- -- -- -- -- -- -- -- -- -- -- --  
      --- Partition By Customer ---
-- -- -- -- -- -- -- -- -- -- -- -- -- 
MAX ORDRQTY = 
    CALCULATE(
        MAX('Generic Sales'[ORDER_QTY]),
        ALLEXCEPT('Generic Sales', 'Generic Sales'[CUST_NAME])
    )


  
-- -- -- -- -- -- -- -- -- -- -- -- -- 
      --- Forecast Growth % ---
-- -- -- -- -- -- -- -- -- -- -- -- -- 
Avg. Growth % = 
VAR diff23 = IF([CY_2023] + [CY_2022] <> 0, MIN(([CY_2023] - [CY_2022]) / ([CY_2023] + [CY_2022]), 1), 0)
VAR diff24 = IF([CY_2024] + [CY_2023] <> 0, MIN(([CY_2024] - [CY_2023]) / ([CY_2024] + [CY_2023]), 1), 0)
VAR diff25 = IF([CY_2025] + [CY_2024] <> 0, MIN(([CY_2025] - [CY_2024]) / ([CY_2025] + [CY_2024]), 1), 0)
VAR CurrMonth = MONTH(TODAY())

RETURN
IF( 
    [CY_2025] + [CY_2024] = 0, 0,
    IF(
        SalesTable[calendarMonth] < CurrMonth,
        MAX((diff23 + (diff24) + (diff25)) / 3, -1),
        MAX((diff23 + (3*diff24)) / 4, -1)
))


  
-- -- -- -- -- -- -- -- -- -- -- -- -- 
      --- Forecast w/ Products ---
-- -- -- -- -- -- -- -- -- -- -- -- -- 
2026 FORECAST = 
VAR SumSales =
    (1 * [CY_2022]) +
    (2 * [CY_2023]) +
    (3 * [CY_2024]) +
    (4 * [2025 PRJ. FINISH])
VAR BaseForecast = SumSales / 10
VAR CategoryAdj = SWITCH (
        SalesTable[Category],
        "Steel Pipe", BaseForecast * (1 - 0.55),
        "Flex Products", BaseForecast * (1 + 1.5 * [AVG% DIFF]),
        "Grooved", BaseForecast * (1 + 2 * [AVG% DIFF]),
        "FAB", 0,
        BaseForecast * (1 + [AVG% DIFF])
        )
RETURN
    IF (
        [2025 PRJ. FINISH] = 0 || SalesTable[VNDID] = "TGI05" || SalesTable[VNDID] = "",
        0,
        CategoryAdj
    )


  
-- -- -- -- -- -- -- -- -- -- -- -- -- 
--- Forecast Current Year Growth % ---
-- -- -- -- -- -- -- -- -- -- -- -- -- 
2025 Revenue Growth% = 
VAR CurrentDate = TODAY()
VAR LastFullMonth = MONTH(EOMONTH(CurrentDate, -1))
VAR Revenue2025 =
    CALCULATE(
        [Revenue 2025],
        FILTER(
            'Sales_Normal',
            YEAR('Sales_Normal'[invoiceDate]) = 2025 &&
            MONTH('Sales_Normal'[invoiceDate]) <= LastFullMonth
        )
    )
VAR Revenue2024 =
    CALCULATE(
        [Revenue 2024],
        FILTER(
            'Sales_Normal',
            YEAR('Sales_Normal'[invoiceDate]) = 2024 &&
            MONTH('Sales_Normal'[invoiceDate]) <= LastFullMonth
        )
    )
VAR Diff = Revenue2025 - Revenue2024
VAR DiffPct = DIVIDE(Diff, Revenue2024)
RETURN
    IF(Revenue2025 > 0, DiffPct, BLANK())

