-- Total business days (3-months)
WITH DAY_COUNT_TOTAL AS (
SELECT COUNT(*) AS TOTAL_DAYS
FROM DimDate
WHERE calendardate >= DATEADD(MONTH, -4, GETDATE())
      AND calendardate < DATEADD(MONTH, -1, GETDATE())
      AND businessDay = 'Y'
),

-- 3-month Moving Qty Sold 
THREE_MO_INVOICE AS (
SELECT 
	ITEM, SUM(QTYSHIP) AS QTYSOLD
FROM InvoiceDetailHistory I
    INNER JOIN DimDate DT 
		ON DT.CALENDARDATE = I.invoiceDate
WHERE calendardate >= DATEADD(MONTH, -4, GETDATE())
      AND calendardate < DATEADD(MONTH, -1, GETDATE())
GROUP BY ITEM
),

-- Join DCSDIM Price
SALES AS(
SELECT 
	ITEM, C.VNDID, C.TRGTPUR,
	SUM(QTYSOLD) AS THREE_MO_QTYSOLD
FROM THREE_MO_INVOICE T
JOIN DCSCIM C ON 
	C.ITMID = T.ITEM
GROUP BY ITEM, VNDID, C.TRGTPUR
),

-- Aggregate Qty & Cost
SALES_COST AS(
SELECT 
	VNDID, 
	SUM(THREE_MO_QTYSOLD) AS THREE_MO_QTYSOLD, 
	SUM(THREE_MO_QTYSOLD*TRGTPUR) AS THREE_MO_COST
FROM SALES
GROUP BY VNDID
),

-- Final Sales Table
FINAL_SALES AS(
SELECT *
FROM SALES_COST
),

-- Warehouse Inventory by ITMID
DIM AS(
SELECT 
	D.ITMID, D.VNDID, C.TRGTPUR,
	SUM(OHQTY) AS OHQTY, 
	SUM(POONORDQTY) AS ONORDRQTY, 
	SUM(OUTSTKQTY) AS BCKORDRQTY, 
	SUM(COPSALCQTY) AS ALCQTY 
FROM DCSDIM D
JOIN DCSCIM C 
	ON C.ITMID = D.ITMID
GROUP BY D.ITMID, D.VNDID, C.TRGTPUR, D.POONORDQTY
),

-- Item Status Calc
DIM_ITMSTS AS(
SELECT *, (OHQTY - (BCKORDRQTY+ALCQTY)) AS ITMSTS
FROM DIM
),

-- Multiply Cost by Qty (Inventory Value)
DIM_COST AS(
SELECT 
	ITMID, VNDID, 
	SUM(ITMSTS) AS ITMSTS_QTY,
	SUM(ONORDRQTY) AS ONORDRQTY,
	SUM(BCKORDRQTY) AS BCKORDRQTY,
	CASE 
		WHEN SUM(TRGTPUR*ITMSTS) < 0 THEN 0
		ELSE SUM(TRGTPUR*ITMSTS) END AS ITMSTS_COST
FROM DIM_ITMSTS
GROUP BY ITMID, VNDID
),

-- Aggredate Inventory Qty & Cost by ITMID
FINAL_DIM AS(
SELECT 
	VNDID, 
	SUM(ITMSTS_QTY) AS ITMSTS_QTY, 
	SUM(ONORDRQTY) AS ONORDRQTY,
	SUM(BCKORDRQTY) AS BCKORDRQTY,
	SUM(ITMSTS_COST) AS ITMSTS_COST
FROM DIM_COST
GROUP BY VNDID
),

-- JOIN Sales and Warehouse Data
JOINED AS(
SELECT 
	D.VNDID, D.ITMSTS_QTY, D.ONORDRQTY, D.BCKORDRQTY, D.ITMSTS_COST, 
	S.THREE_MO_QTYSOLD, S.THREE_MO_COST,
	CY.TOTAL_DAYS
FROM FINAL_DIM D
JOIN FINAL_SALES S
	ON D.VNDID = S.VNDID
CROSS JOIN DAY_COUNT_TOTAL CY
WHERE D.VNDID <> ''
),

-- Find Daily Demand Qty and Cost
DAILY_DMD AS(
SELECT 
	*, 
	(THREE_MO_QTYSOLD/TOTAL_DAYS) AS DAILY_DMD_QTY,
	(THREE_MO_COST/TOTAL_DAYS) AS DAILY_DMD_COST
FROM JOINED
),

-- Find DOH value (Total / Daily)
DOH AS(
SELECT *, 
	CASE 
		WHEN DAILY_DMD_QTY <> 0 THEN CAST(ROUND((ITMSTS_COST/DAILY_DMD_QTY),1) AS decimal (18,1))
		ELSE 0 END AS DOH_QTY,
	CASE 
		WHEN DAILY_DMD_COST <> 0 THEN CAST(ROUND((ITMSTS_COST/DAILY_DMD_COST),1) AS decimal (18,1))
		ELSE 0 END AS DOH
FROM DAILY_DMD
),

-- Select Columns
FINAL AS(
SELECT 
	VNDID, 
	ITMSTS_QTY, ONORDRQTY, BCKORDRQTY, DAILY_DMD_QTY,
	ITMSTS_COST, DAILY_DMD_COST, DOH
FROM DOH
)

-- Filter VNDID
SELECT *
FROM FINAL
WHERE VNDID IN (
	'SPE49','API02','PHD27','WAT81','LAI26','PES01',
	'SAF04','APD10','GMC22','PSB24','ITW92','CAR65')
ORDER BY VNDID ASC;

-- RETURN:

-- VNDID	ITMSTS_QTY	ONORDRQTY	BCKORDRQTY	DAILY_DMD_QTY	ITMSTS_COST	DAILY_DMD_COST	DOH
-- APD10       	1	  	  6	  	  7	  	   2	  	  	 80	  	  	  16	  	  5
-- API02       	2	  	  7	 	    9	  	   4	  	  	 60	  	  	  32	  	  5
-- CAR65       	3	  	  8	 	    11		   6	  	  	 240	  	  	48	  	  5
-- GMC22       	4	  	  9	 	    13		   8	  	  	 320	  	  	64	 	    5
-- ITW92       	5	  	  10	  	15		   10		  	   400	  	  	80	  	  5
-- LAI26       	6	  	  11		  17		   12		  	   480	  	    96	  	  5
-- PES01       	7	  	  12		  19		   14		  	   560	  	  	112	  	  5
-- PHD27       	8	  	  13		  21		   16		  	   640	  	  	128	  	  5
-- PSB24       	9	  	  14		  23		   18		  	   720	  	  	144	  	  5
-- SAF04       	10		  15		  25		   20		  	   800	  	  	160	  	  5
-- SPE49       	11		  16		  27		   22		  	   880	  	    176	  	  5
-- WAT81       	12		  17		  29		   24		 	     960	  	  	192	  	  5
