-- CTE Sales Table
WITH CUSTOMER_TABLE AS(
  SELECT 
	  CSTNAM AS CUST_NAME, 
	  SUM(QTYSHIP) AS ORDER_QTY, 
	  SUM(QTYSHIP*UNITPRICE) AS SALES_REVENUE, 
	  CAST(invoiceDate AS DATE) AS INVOICE_DATE
  FROM Sales_table
  WHERE fiscalYear = '2025'
  GROUP BY CSTNAM, invoiceDate
)

-- Partition By clauses for MIN/MAX by Customer
SELECT *,
	MAX(ORDER_QTY) OVER(PARTITION BY CUST_NAME ORDER BY ORDER_QTY DESC) AS MAX_ORDER_QTY,
	MIN(ORDER_QTY) OVER(PARTITION BY CUST_NAME ORDER BY ORDER_QTY ASC) AS MIN_ORDER_QTY
FROM CUSTOMER_TABLE
ORDER BY CUST_NAME
