WITH VCH_DATES AS(
	SELECT M3.PONBR, M3.PLT, M3.ISSDTE, C.VNDID, D.CALENDARDATE,
		DATEDIFF(DAY, LAG(D.CALENDARDATE) OVER (PARTITION BY C.VNDID, M3.PLT ORDER BY D.CALENDARDATE ASC), D.CALENDARDATE) AS DaysBetween

	FROM DPMORDM3 M3
	JOIN DPMORDM0 M0 
		ON M3.PONBR = M0.PONBR
	INNER JOIN DIMDATE D
		ON M3.ISSDTE = D.julianDate
	LEFT JOIN DCSCIM C 
		ON C.ITMID = M3.ITMID
	WHERE calendarYear >= '2025' AND COPCLSCD = 'RSLE' AND M3.ITMID <> 'CANCELLED' AND M0.POTYP = 'R'
	GROUP BY M3.PONBR, M3.PLT, M3.ISSDTE, C.VNDID, D.CALENDARDATE
),


DAY_RANGE AS(
	SELECT *,
		MAX(DaysBetween) OVER (PARTITION BY VNDID, PLT) 
		- MIN(DaysBetween) OVER (PARTITION BY VNDID, PLT) AS Day_Range
	FROM VCH_DATES
),


GROUPED AS(
	SELECT PLT, VNDID,
		CAST(AVG(DAYSBETWEEN) AS DECIMAL (10,4)) AS Avg_Days_Between, CAST(AVG(DAY_RANGE) AS DECIMAL (10,4)) AS DaysRange
	FROM DAY_RANGE
	GROUP BY PLT, VNDID
),


RATIO AS(
	SELECT *, 
	CASE WHEN Avg_Days_Between = 0 THEN 0 ELSE ROUND((DaysRange / Avg_Days_Between), 4) END AS DaysRatio
	FROM GROUPED
),


ITEM_CATEGORY AS(
	SELECT *,
	CASE 
		WHEN DaysRatio > 2   THEN '4 Extreme Flux'
		WHEN DaysRatio > 1   THEN '3 Mild Flux'
		WHEN DaysRatio > 0.5 THEN '2 Average Flux'
		ELSE '1 Steady' END as Category
	FROM RATIO
)


SELECT *
FROM ITEM_CATEGORY
ORDER BY PLT, Category ASC;
