-- Create & Filter PO Table
WITH VCH_DATES AS(
  SELECT PLT, M3.PONBR, M3.VNDID, LSTRECPDTE, D.CALENDARDATE
  FROM DPMORDM3 M3
  INNER JOIN DimDate D 
	  ON D.mdyDate = M3.LSTRECPDTE
  JOIN DPMORDM0 M0 
	  ON M3.PONBR = M0.PONBR
  JOIN DCSCIM C
	  ON C.ITMID = M3.ITMID
  WHERE calendarYear >= '2025' AND M0.POTYP = 'R' AND COPCLSCD = 'RSLE'
  GROUP BY PLT, M3.PONBR, M3.VNDID, LSTRECPDTE, D.CALENDARDATE  -- Must GROUP BY to remove duplicate records from ITMID column
),

-- Find Date_Diff for Each PO by Vendor and Location
DATES_DIFF AS(
SELECT *, DATEDIFF(DAY, LAG(CALENDARDATE) OVER (PARTITION BY VNDID, PLT ORDER BY CALENDARDATE), calendarDate) AS DATE_DIFF
FROM VCH_DATES
)

-- Average Days Between Order returned:
SELECT 
	PLT, 
	VNDID, 
	CAST(AVG(CAST(DATE_DIFF AS DECIMAL (18,2))) AS DECIMAL (18,2)) AS Avg_Days_Between
FROM DATES_DIFF
WHERE DATE_DIFF IS NOT NULL
GROUP BY PLT, VNDID
ORDER BY PLT
